FROM prestashop/prestashop:1.7.8

RUN rm -rf /var/www/html/*
COPY ./src /var/www/html

COPY ./init.sh /var/www/html/init.sh
COPY ./dump.sql /var/www/html/dump.sql

COPY ./website.cert /etc/ssl/certs/website.cert
COPY ./website.cert /usr/local/share/ca-certificates/website.cert
COPY ./notEncodedPk.key /etc/ssl/private/notEncodedPk.key
COPY ./ssl.conf /etc/apache2/sites-available/ssl.conf

RUN chmod 777 /var/www/html/init.sh && \
    chmod 777 /var/www/html/dump.sql && \
    chmod 777 /etc/ssl/certs/website.cert && \
    chmod 777 /etc/ssl/private/notEncodedPk.key && \
    chmod 777 /etc/apache2/sites-available/ssl.conf && \
    chmod 777 /usr/local/share/ca-certificates/website.cert

RUN usermod -u 1000 www-data

RUN chown -R www-data /etc/apache2/sites-available/

RUN rm -rf /var/www/html/var/cache/* && \
    chown -R www-data:www-data /var/www/html && \
    chmod -R 777 /var/www/html && \
    chmod -R 777 /var/www/html/var/cache /var/www/html/var/logs

RUN apt-get update && \
    apt-get install -y libmemcached-dev zlib1g-dev && \
    pecl install memcached && \
    docker-php-ext-enable memcached

RUN update-ca-certificates && a2enmod ssl && a2ensite ssl && a2enmod rewrite

CMD ["sed -i -e 's/\r$//' ./init.sh"]
CMD ["./init.sh"]