FROM prestashop/prestashop:1.7.8

COPY website.cert:/etc/ssl/certs/website.cert
COPY website.cert:/usr/local/share/ca-certificates/website.cert
COPY notEncodedPk.key:/etc/ssl/private/notEncodedPk.key

COPY ./ssl.conf /etc/apache2/sites-available/ssl.conf

COPY dump.sql /dump.sql
COPY init.sh /init.sh

RUN rm -rf /var/www/html/*
COPY src /var/www/html

RUN rm -rf /var/www/html/var/cache/* && \
    chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html && \
    chmod -R 777 /var/www/html/var/cache /var/www/html/var/logs

RUN apt-get update && \
    apt-get install -y libmemcached-dev zlib1g-dev && \
    pecl install memcached && \
    docker-php-ext-enable memcached

RUN update-ca-certificates && a2enmod ssl && a2ensite ssl && a2enmod rewrite