<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxqddud\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxqddud/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKxqddud.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKxqddud\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKxqddud\appDevDebugProjectContainer([
    'container.build_hash' => 'Kxqddud',
    'container.build_id' => 'fc8c0598',
    'container.build_time' => 1703513949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxqddud');
