<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2wvht3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2wvht3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX2wvht3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX2wvht3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX2wvht3\appDevDebugProjectContainer([
    'container.build_hash' => 'X2wvht3',
    'container.build_id' => '7c74ef47',
    'container.build_time' => 1703549077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2wvht3');
