<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQiumzzt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQiumzzt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQiumzzt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQiumzzt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQiumzzt\appDevDebugProjectContainer([
    'container.build_hash' => 'Qiumzzt',
    'container.build_id' => '84091dfe',
    'container.build_time' => 1703364885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQiumzzt');
